### ISSUE TITLE
Recent GetObjectType additions don't compile on x86

### ISSUE THREAD

**Issue by romanl-g** [KhronosGroup/Vulkan-Utility-Libraries#138]
@charles-lunarg @mikes-lunarg 

Looks like one of the GetObjectType commits on Oct 4 introduced this. Some of our builds are ok, but multiple builds are failing.

https://ci.chromium.org/ui/p/angle/builders/try/win-x86-test/15700/overview
https://logs.chromium.org/logs/angle/buildbucket/cr-buildbucket/8768076008413092417/+/u/compile/stdout

```
../../third_party/vulkan-deps/vulkan-utility-libraries/src/include\vulkan/utility/vk_struct_helper.hpp(1179,32): error: redefinition of 'GetObjectType<unsigned long long>'
 1179 | template<> inline VkObjectType GetObjectType<VkImage>() { return VK_OBJECT_TYPE_IMAGE; }
      |                                ^
../../third_party/vulkan-deps/vulkan-utility-libraries/src/include\vulkan/utility/vk_struct_helper.hpp(1178,32): note: previous definition is here
 1178 | template<> inline VkObjectType GetObjectType<VkBuffer>() { return VK_OBJECT_TYPE_BUFFER; }
```
(and other errors)

**Comment by romanl-g** [comment]
Not 100% sure x86 is the root cause but seems likely

**Comment by romanl-g** [comment]
Note: broken with this commit included https://github.com/KhronosGroup/Vulkan-Utility-Libraries/commit/f528b23aecb852b23e64bf83ff459b3698313b82

**Comment by charles-lunarg** [comment]
The PR I just made makes GetObjectType not defined in 32 bit builds.

**Comment by charles-lunarg** [comment]
@ben-clayton @romanl-g Would appreciate it if you were able to verify that this fixes the issue. Of course, I intend to merge this as soon as possible, so the breakage is as short as possible.

**Comment by romanl-g** [comment]
Will take some time to get a roll through but I checked locally and an Android build that includes 32-bit libraries was broken this way before and does compile now. Thanks!

**Comment by juan-lunarg** [comment]
I have a PR that adds a 32 bit Arm build to CI to prevent this type of issue in the future.
https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/142
