### ISSUE TITLE
Remove `BUILD_LAYER_SUPPORT_FILES` from the vulkan validation layers

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Utility-Libraries#18]
The ultimate goal of this repo is that the validation layers will no longer need to install header/source files anymore.

The vulkan validation layer repo was never meant for shipping header / source files.

It's only deliverables are a shared library, and a json file. All other files are unintended artifacts resulting from the days everything was in a mono repo.

Instead of the validation layers facilitating code sharing across vulkan repos, it will now be the responsibility of the utility libraries.

This is better for all parties since validation layers developers won't have to worry about unintentionally breaking downstream users. And users get proper source deliverables.

**Comment by juan-lunarg** [comment]
Half way there now that profiles no longer uses VVL.

**Comment by juan-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6468

**Comment by jiriks74** [comment]
Hello. I'm sorry but I'm now having trouble compiling [vkdevicechooser](https://github.com/aejsmith/vkdevicechooser) which I need to run things on my Intel iGPU as the Intel Arc dGPU is quite unstable in some games.

I have no idea where to get the required `vk_layer_dispatch_table.h` header file anymore. What do I need to do to get it?

**Comment by juan-lunarg** [comment]
> I have no idea where to get the required `vk_layer_dispatch_table.h` header file anymore. What do I need to do to get it?

`vk_layer_dispatch_table.h` is now `vk_dispatch_table.h`

https://github.com/KhronosGroup/Vulkan-Utility-Libraries/blob/main/include/vulkan/utility/vk_dispatch_table.h

FYI @charles-lunarg

**Comment by jiriks74** [comment]
Thanks @charles-lunarg 
But I guess that changes are needed to the source code of the `vkdevicechooser`? I changed it to this library and got quite a lot of errors while compiling it.

**Comment by juan-lunarg** [comment]
> But I guess that changes are needed to the source code of the `vkdevicechooser` ? I changed it to this library and got quite a lot of errors while compiling it.

Yes it will require updating the code.

**Comment by jiriks74** [comment]
Thanks for the help! It's done as the code isn't that complicated and I didn't really have to do anything as the LSP figured out what to change for the most part.

**Comment by charles-lunarg** [comment]
If you are on linux, you can use the mesa device select layer to accomplish the same goal.
https://docs.mesa3d.org/envvars.html#vulkan-mesa-device-select-layer-environment-variables
It may be able to do everything you need and is maintained by the mesa folks.

**Comment by jiriks74** [comment]
> If you are on linux, you can use the mesa device select layer to accomplish the same goal.
> https://docs.mesa3d.org/envvars.html#vulkan-mesa-device-select-layer-environment-variables
> It may be able to do everything you need and is maintained by the mesa folks.

Thanks, I'll look into it. So far I've quickly patched it so that [*it just works*](https://youtu.be/YPN0qhSyWy8).

It would be cool if it worked with just mesa as everyone has that already installed. Now that I have a fork I may port it over once I have time to go over the code (and understand it - I've never messed around with GPUs like this).

**Comment by charles-lunarg** [comment]
The device select layer is installed by default iirc, not sure which package is responsible for it.
