### ISSUE TITLE
vk_typemap_helper.h

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Utility-Libraries#74]
Both VVL and VEL have the same helper file:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/vulkan/generated/vk_typemap_helper.h
https://github.com/KhronosGroup/Vulkan-ExtensionLayer/blob/main/utils/generated/vk_typemap_helper.h

**Comment by charles-lunarg** [comment]
Three repos!
https://github.com/KhronosGroup/Vulkan-Tools/blob/main/icd/generated/vk_typemap_helper.h
