### ISSUE TITLE
Minimize CMake flags developer has to set

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Utility-Libraries#97]
Instead of `-D VUL_WERROR=ON -D BUILD_TESTS=ON  -D UPDATE_DEPS=ON` etc.

Have 1 build option that sets it all up.

`-D VLK_DEV=ON`

IE the intent is to streamline the workflow for developers.

**Comment by christophe-lunarg** [comment]
The -D VLK_DEV=ON settings should also encapsulate the warning levels used by C.I.

**Comment by juan-lunarg** [comment]
> The -D VLK_DEV=ON settings should also encapsulate the warning levels used by C.I.

Yes both CI and local developers would be able to use it.
