### ISSUE TITLE
Project description missing

### ISSUE THREAD

**Issue by tgurr** [KhronosGroup/Vulkan-Utility-Libraries#99]
Since https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/334870942c4185592b82f39487806e2db63f0ae7 which is included in v1.3.263 this is a requirement to build Vulkan-ValidationLayers now, however essential parts are missing, no tag, no proper description in README.md or Project "About". It would have been really nice to have had these things addressed **before** tagging a new version depending on it.

**Comment by juan-lunarg** [comment]
There is an existing v1.3.263 tag https://github.com/KhronosGroup/Vulkan-Utility-Libraries/releases/tag/v1.3.263

Not sure what you mean by the tag.

The rest will be addressed in time for the next SDK release.

**Comment by tgurr** [comment]
> There is an existing v1.3.263 tag https://github.com/KhronosGroup/Vulkan-Utility-Libraries/releases/tag/v1.3.263
> 
> Not sure what you mean by the tag.

I have to apologize, probably since there haven't been any releases github doesn't show the usual info on the left side of the project also mentioning tags:

![image](https://github.com/KhronosGroup/Vulkan-Utility-Libraries/assets/414984/f8c98d1e-d819-4410-97fc-9500f2d61083)

so I didn't realize there are indeed tags available, huge sorry for complaining!

> The rest will be addressed in time for the next SDK release.

Thanks!
